Added an exclamation point (!)
CurtisGreen/dallas-area-transit-alliance pull request #23
Opened 2024-07-31 03:32 UTC by LEQUI000

2024-07-31 03:34 UTC, Schobbish commented
![great_find_1024x](https://github.com/user-attachments/assets/73282700-5e31-49c8-88cf-a99dc8898f7d)

2024-07-31 03:39 UTC, LEQUI000 commented
We can decide whether or not to add an exclamation or not.

2024-07-31 05:54 UTC, democat3457 commented
(for posterity) imo the period is more professional

2024-08-01 00:04 UTC, Schobbish requested changes

2024-08-01 00:04 UTC, Schobbish commented on _posts/data-announces-formation.md
> +  text: "Read our latest press release announcing our formation!"
Replace exclamation mark with period

2024-08-01 00:22 UTC, Schobbish approved these changes

2024-08-01 00:28 UTC, merged